### ISSUE TITLE
csv_embedding throwing errors

### ISSUE THREAD

**Issue by staru09** [GaiaNet-AI/embedding-tools#2]
I am not very sure if it's an issue but a few days back I used [this](https://github.com/GaiaNet-AI/embedding-tools/tree/main/csv_embed) to generate a snapshot and it was working fine but now it's giving error message as shown below.

![Screenshot from 2024-09-12 07-26-23](https://github.com/user-attachments/assets/279b81ad-c262-4c53-8380-677032b2295e)

[This](https://huggingface.co/datasets/FiendHunter/Github_bot/resolve/main/final_output_llama.csv) is where my csv file is stored and this is the command I ran
wasmedge --dir .:. \
--nn-preload embedding:GGML:AUTO:nomic-embed-text-v1.5.f16.gguf \
csv_embed.wasm embedding default final_output_llama.csv --ctx_size 8192

Using this same command I was able to generate this [snapshot](https://huggingface.co/datasets/FiendHunter/Financial_chatbot/blob/main/summary_qna.tar.gz) from this [csv](https://github.com/staru09/LFX_test/blob/main/Financial_chatbot/Dataset/CSV/out_summary.csv) file

**Comment by juntao** [comment]
You did not give the vector size ...

**Comment by staru09** [comment]
Thanks a lot @juntao sir
I totally missed it
It's working fine now
